### ISSUE TITLE
closureLanguageOut ECMASCRIPT5 should not enforce STRICT mode

### ISSUE THREAD

**Issue by blutorange** [blutorange/closure-compiler-maven-plugin#19]
<a href="https://github.com/ph3n0m666"><img src="https://avatars3.githubusercontent.com/u/4669456?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ph3n0m666](https://github.com/ph3n0m666)**
_Tuesday Mar 21, 2017 at 10:31 GMT_
_Originally opened as https://github.com/samaxes/minify-maven-plugin/issues/138_

----

It seems, using 1.7.6 specifying ECMASCRIPT5 in closureLanguageIn/closureLanguageOut, is returning the following

 object literals cannot contain duplicate keys in ES5 strict mode - but I am not specifying ECMASCRIPT5_STRICT - only ECMASCRIPT5

**Comment by blutorange** [comment]
<a href="https://github.com/cqxxxxxxxx"><img src="https://avatars2.githubusercontent.com/u/4110460?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cqxxxxxxxx](https://github.com/cqxxxxxxxx)**
_Tuesday May 09, 2017 at 13:43 GMT_

----

this cames to me too.  how you fix this?

**Comment by blutorange** [comment]
<a href="https://github.com/ph3n0m666"><img src="https://avatars3.githubusercontent.com/u/4669456?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ph3n0m666](https://github.com/ph3n0m666)**
_Tuesday May 09, 2017 at 13:57 GMT_

----

Have not been able to fix this yet, still an open issue for me

**Comment by blutorange** [comment]
<a href="https://github.com/rtomsick"><img src="https://avatars3.githubusercontent.com/u/1508434?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rtomsick](https://github.com/rtomsick)**
_Tuesday Jun 26, 2018 at 18:14 GMT_

----

Still there, still a bug.

This project is pretty much abandoned, right?

**Comment by blutorange** [comment]
This is a wrapper for closure compiler. This seems to be an issue with closure compiler itself. I can reproduce with the command line of closure compiler, even when disabling errors:

```bash
java -jar closure-compiler-v20181008.jar --language_in ECMASCRIPT_2016 --language_out ECMASCRIPT3 /tmp/test.js --jscomp_off es5Strict
```

**Comment by nitehawk42** [comment]
Is there a non-abandoned maven plugin for this? I need something that actually exposes the options of GCC.

**Comment by nitehawk42** [comment]
Is there a non-abandoned maven plugin project for closure-compiler?

**Comment by blutorange** [comment]
@nitehawk42 What do you mean? I'm still working on this plugin, although currently there's not much more to do than ocassionally updating closure compiler to the latest version. If there's a new closure compiler you need quickly, feel free to tell me and I can release a new version of this plugin. As for this issue, I kept it open, but the behavior is how closure compiler works.

**Comment by blutorange** [comment]
Closing as this is an issue of closure compiler itself (which may or may not have been changed in the recent version of closure compiler).
