### ISSUE TITLE
No skip option

### ISSUE THREAD

**Issue by mdgeek** [blutorange/closure-compiler-maven-plugin#49]
Many Maven plugins have a skip config option to conditionally suppress execution.  There appears to be nothing equivalent here (there are a couple of skipXXX options, but they do not suppress execution, only selected behaviors).  Would you consider adding such an option?

**Comment by blutorange** [comment]
Yes, sure. Just to make sure, what you mean is an option `skip=true`, so that the plugin is still executed, but immediately exits without doing anything?

**Comment by mdgeek** [comment]
Yes, exactly.  Thanks.

**Comment by mdgeek** [comment]
Works like a charm!  Thanks.
