### ISSUE TITLE
Add “incremental” build support

### ISSUE THREAD

**Issue by bogdanb** [blutorange/closure-compiler-maven-plugin#51]
I’d really like a way to avoid minifying everything on on each build. Something like `skipIfNewer` which, when `true`, checks if an output file already exists and is newer than the input file and skips minifying that input file in particular.

This is mostly useful when `skipMerge` is true, but it could also make sense in the merged case, you just need to check _all_ input files in that case.

**Comment by blutorange** [comment]
Sounds like a great idea. I already added support for incremental builds in Eclipse. 

Are you talking about incremental builds when using the CLI or another IDE?

**Comment by bogdanb** [comment]
The CLI. I usually run "mvn package" a lot during development (building
Jira add-ons, you need the jar to test any change).

The older minifier did nothing if it found the already-minimized file, so
most test builds effectively skipped that part. I'd like to use closure
instead, but it effectively doubles my build times even if the JS is not
touched.

**Comment by blutorange** [comment]
Yeah, I can understand that. I like your idea with the `skipIfNewer` option. Shouldn't be too hard to implement as the option to skip exists already for the Eclipse incremental build support. I'll take a look at it.

**Comment by blutorange** [comment]
You can  test it out with the SNAPSHOT release if you'd like. I'll probably release version `2.9.0` during the weekend.

These options are the default so you should not have to set them explicitly:

```xml
	<groupId>com.github.blutorange</groupId>
	<artifactId>closure-compiler-maven-plugin</artifactId>
	<version>2.9.0-SNAPSHOT</version>
	<configuration>
		<skipMode>NEWER</skipMode>
		<force>false</force>
	</configuration>
```

**Comment by bogdanb** [comment]
I did a test right now, it works perfectly!

**Comment by bogdanb** [comment]
One thing that might be a good idea is to log an info message about how many files were minimized. (This is probably good in general, but especially useful for when these options are used.) As an example, here‘s how a build log looks in my case:

```
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ rich-filters-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 392 resources
[INFO]
[INFO] --- jira-maven-plugin:8.0.2:filter-plugin-descriptor (default-filter-plugin-descriptor) @ rich-filters-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- closure-compiler-maven-plugin:2.9.0-SNAPSHOT:minify (minify-javascript) @ rich-filters-plugin ---
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:copy-resources (filter-plugin-fragments) @ rich-filters-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:copy-resources (overwrite-plugin-fragments) @ rich-filters-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
```

It would be nice to see for the “minify-javascript” goal something like:
```
[INFO] Minifying 150 resources
[INFO] Skipped 149 already-minified (NEWER)
```

**Comment by blutorange** [comment]
It should already log which files were processed, but I added a summary that looks like this:

```
[INFO] --- closure-compiler-maven-plugin:2.9.0-SNAPSHOT:minify (default-minify) @ closure-compiler-maven-plugin-test-skipsome ---
[INFO] Starting JavaScript task:
[INFO] Skipping the merge step...
[INFO] Creating the minified file [script2.min.js].
[INFO] Uncompressed size: 62 bytes.
[INFO] Compressed size: 76 bytes minified (91 bytes gzipped).
[INFO] Creating the minified file [script5.min.js].
[INFO] Uncompressed size: 63 bytes.
[INFO] Compressed size: 76 bytes minified (91 bytes gzipped).

[INFO] Processed 5 output files
[INFO] Created 2 output files
[INFO] Skipped 3 output files (EXISTS)
```
