### ISSUE TITLE
'js' target dir is created even with a different targetDir

### ISSUE THREAD

**Issue by lonemadmax** [blutorange/closure-compiler-maven-plugin#54]
This is just a cosmetic issue. An empty directory is created with the default target name when a different one is specified through the targetDir tag. The merged/minified files are correctly created in the specified target dir.

**Comment by blutorange** [comment]
Do you mean the option `targetDir` (which to defaults to `js`). It doesn't seem to be creating directories for me (and the default value `js` should be overwritten by maven before this plugin even gets to see it). 

Can you post the your configuration from the `pom.xml`?

**Comment by lonemadmax** [comment]
:flushed: My fault, and my fault only.

The directory appeared when I was trying to move a project from samaxes' minify-maven-plugin to this one, so I 'obviously' blamed closure-compiler-maven-plugin. Too fast. I couldn't reproduce it while trying to set up a minimum pom (when will users learn to do that *before* opening an issue?), until I went back to having all plugins, including minify-maven-plugin for the css.

So there. It was minify-maven-plugin, running its js tasks with default values even though there's no js includes for it.

I'm sorry I made you waste time on this.

**Comment by blutorange** [comment]
No problem, you're welcome. It was a good opportunity to update closure-compiler to the latest version ; )

Since you're mentioning CSS, I'm personally using the [warmuuh/libsass-maven-plugin](https://github.com/warmuuh/libsass-maven-plugin), which gives you all the awesome features of a CSS preprocessor : )
