### ISSUE TITLE
Upgrade Closure Compiler to at least v20200504

### ISSUE THREAD

**Issue by mzaum** [blutorange/closure-compiler-maven-plugin#55]
Google recommends not using v20200426.

Per their [release notes](https://github.com/google/closure-compiler/wiki/Releases):

Note: A [problem](https://github.com/google/closure-compiler/issues/3587) was discovered with this release after most of the work to publish it was already complete, so we did another release the following week with that problem fixed and do not recommend using this one.

**Comment by blutorange** [comment]
Thanks for informing me, and update is overdue anyway, so I'll update soon.

**Comment by blutorange** [comment]
Version 2.17.0 of this plugin should be available now.
