### ISSUE TITLE
Build failure: Unable to parse configuration of mojo com.github.blutorange:closure-compiler-maven-plugin:2.21.0:minify for parameter includes: Cannot assign configuration entry 'includes' with value '**/*.js' of type java.lang.String to property of type java.util.ArrayList

### ISSUE THREAD

**Issue by naomidhanapal** [blutorange/closure-compiler-maven-plugin#58]
Using Version 2.21.0
I get the build failure: **Unable to parse configuration of mojo com.github.blutorange:closure-compiler-maven-plugin:2.21.0:minify for parameter includes: Cannot assign configuration entry 'includes' with value `'**/*.js'` of type java.lang.String to property of type java.util.ArrayList**, when I have `<includes>**/*.js<includes>` in my pom.

This issue can be solved with the additional `<include>` parameter in my pom:

`<includes><include>**/*.js</include></includes>`

**Comment by blutorange** [comment]
Yes, the`includes` is a list, so you need `<includes><include>**/*.js</include></includes>`. The parsing is done by maven itself, so I don't think there's any way to support the shortcut `<includes>**/*.js<includes>`.

With the long version you don't get any issues?

**Comment by naomidhanapal** [comment]
With the long version, I don't get any issues. However, I think it would be great to add it to the usage example in the README.md.

**Comment by blutorange** [comment]
Ah, now I see what you mean, it's wrong in the readme. I updated it, thanks for pointing it out :+1:
