### ISSUE TITLE
"Fork me on github" link contains typo

### ISSUE THREAD

**Issue by svschouw-bb** [blutorange/closure-compiler-maven-plugin#61]
The "Fork me on github" link on the [maven site](https://blutorange.github.io/closure-compiler-maven-plugin/minify-mojo.html) points to https://github.com/bluorange/closure-compiler-maven-plugin, which is missing a "t" in blutorange and results in a 404 page.

**Comment by blutorange** [comment]
Thanks for pointing this out, I fixed the spelling mistake. I'll update the the site when I can.
