### ISSUE TITLE
closure-compiler-maven-plugin fails to compile if web folder is empty or does not exist

### ISSUE THREAD

**Issue by suneet-gupta** [blutorange/closure-compiler-maven-plugin#64]
closure-compiler-maven-plugin fails to compile if web folder is empty ( not having any js files) or does not exist.

Error received when web folder does not exist -
Failed to execute goal com.github.blutorange:closure-compiler-maven-plugin:2.26.0:minify (compress-assembly) on project allinone-test-run: Execution compress-assembly of goal com.github.blutorange:closure-compiler-maven-plugin:2.26.0:minify failed: basedir C:\New folder5\alfresco-sdk\archetypes\archetypes-it\target\test-classes\allinone-test-run\src\main\assembly\web does not exist ->

Error received when web folder exist but there are no js files in it -
org.apache.maven.it.VerificationException: Error in execution: [ERROR] No valid JavaScript source files found to process.

Could you please help on this.

**Comment by blutorange** [comment]
If I understand this correctly, it's failing because it does not find any JavaScript files to bundle or minify. Is this intentional that you want to run the plugin on any input files, or is the plugin supposed to do something, but the directory is wrong?

I could change it so the plugin simply does nothing when it doesn't find any input, although this could be considered a configuration error, hence why it currently emits an error. I'd probably add an option `<failOnMissingInput></failOnMissingInput>` to the plugin, would that solve your issue?

**Comment by suneet-gupta** [comment]
Yes, that should solve the issue. Previously we using yuicompressor-maven -plugin but it was not able to minify js files. We are looking to migrate it to closure-compiler-maven-plugin now. Just to add, yuicompressor-maven-plugin didn't throw error on missing inputs, rather it used to succesfully compile. Thanks.

**Comment by suneet-gupta** [comment]
one query..can we get this fix early. Appreciate your help on this.

**Comment by blutorange** [comment]
Shouldn't be too hard to fix. I'm busy right now but I'll take a look at it later this day.

**Comment by blutorange** [comment]
Ok, so I took a look at it.

The first error

> plugin:2.26.0:minify failed: basedir C:\New folder5\alfresco-sdk\archetypes\archetypes-it\target\test-classes\allinone-test-run\src\main\assembly\web does not exist ->

is definitely wrong and I'll fix that.

The second "error"

![image](https://github.com/blutorange/closure-compiler-maven-plugin/assets/2456413/dabf690b-933b-4081-8433-38dc1deaef42)

is just a log message, it does not fail the build. I can reduce the log level to `warn` though if that is a problem for you.

**Comment by blutorange** [comment]
I released version 2.28.0, if it's still not working please feel free to reopen
