### ISSUE TITLE
java.io.IOException bad pathname

### ISSUE THREAD

**Issue by roojsa** [blutorange/closure-compiler-maven-plugin#68]
Using Windows 11 ( may not be relevant), getting a java.io.IOException

      <plugin>
        <groupId>com.github.blutorange</groupId>
        <artifactId>closure-compiler-maven-plugin</artifactId>
        <version>2.30.0</version>
		<configuration>
			<baseSourceDir>${basedir}/src/main/webapp</baseSourceDir>
		</configuration>
        <executions>
          <execution>
            <id>default-minify</id>
            <configuration>
			  <encoding>UTF-8</encoding>
              <sourceDir>scripts</sourceDir>
              <targetDir>scripts</targetDir>
              <skipMerge>false</skipMerge>
              <closureLanguageOut>ECMASCRIPT5</closureLanguageOut>
              <outputFilename>**/scripts/conxons.min.js</outputFilename>
              <includes>
					<include>close.js</include>
					<include>date.js</include>
			  </includes>
              <excludes><exclude>**/*.min.js</exclude></excludes>
            </configuration>
            <goals>
              <goal>minify</goal>
            </goals>
            <phase>generate-resources</phase>
          </execution>
        </executions>
      </plugin>	

debug output when running

DEBUG] Adding source file [C:\Projects\Dev\Conxons\src\main\webapp\scripts\close.js].
[DEBUG] Adding source file [C:\Projects\Dev\Conxons\src\main\webapp\scripts\date.js].
[INFO] Starting JavaScript task:
[ERROR] Failed to process the source files [close.js, date.js].
java.io.IOException: Bad pathname
	at java.base/java.io.WinNTFileSystem.canonicalize0(Native Method)
	at java.base/java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:463)
	at java.base/java.io.File.getCanonicalPath(File.java:626)
	at com.github.blutorange.maven.plugin.closurecompiler.common.FileHelper.relativizePath(FileHelper.java:31)
	at com.github.blutorange.maven.plugin.closurecompiler.common.FilenameInterpolator.interpolate(FilenameInterpolator.java:38)

**Comment by roojsa** [comment]
Figured it out, i had a misconfiguration in the way I was making the merged .min.js file. It might be useful for a slightly more informative error message there, but not a big deal either way.

**Comment by blutorange** [comment]
Thanks for reporting. Hmm, I'm not sure what exactly was bad about the pathname, but I guess I should at least include the pathname in the error message, to make it easier to debug.

**Comment by roojsa** [comment]
Non-existant path, I was figuring out how to manipulate sourceDir and TargetDir parameters. I thought the issue was in the sourceDir and was going in circles on that until I went through the source in github for a few minutes and realized the error had to be coming from the target side.

Joe Alexander
Service Delivery Manager
Ross Group Inc
MemberzPlus Membership Management
Performance One Data Solutions
3400 Chapel Hill Rd, Suite 100, Douglasville, GA 30135

Mobile: 937.570.1069
Direct:   937.912.3333
Office:    800.652.4985 ext. 1233
Email:    ***@***.******@***.***>
[A picture containing qr code  Description automatically generated]<http://www.performanceonedatasolutions.com/>
[Text  Description automatically generated with medium confidence]<http://www.memberzplus.com/>
